/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_server_mediamanager_HelloWorld */

#ifndef _Included_com_server_mediamanager_HelloWorld
#define _Included_com_server_mediamanager_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_server_mediamanager_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_server_mediamanager_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
